AllCops:
  TargetRubyVersion: 2.3

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 50

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 60

Style/IfUnlessModifier:
  Enabled: false